version: '3'
services:
  app:
    build: .
    ports:
      - '8001:8001'
    environment:
      - PORT=8001
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - .:/app
